# Generated by Django 5.1.6 on 2026-04-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('resumo', models.CharField(blank=True, max_length=300)),
                ('conteudo', models.TextField()),
                ('imagem_url', models.URLField(blank=True)),
                ('link_externo', models.URLField(blank=True)),
                ('destaque', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cms_artigo',
                'ordering': ['-publicado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CardInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=240)),
                ('link_url', models.URLField(help_text='Aceita URL externa, incluindo pastas do Nextcloud')),
                ('icone', models.CharField(blank=True, max_length=40)),
                ('cor_fundo', models.CharField(default='#E7F1FF', max_length=7)),
                ('cor_texto', models.CharField(default='#111111', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_card_informativo',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_portal', models.CharField(default='SIIA 2.0', max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('cor_primaria', models.CharField(default='#1351B4', max_length=7)),
                ('cor_secundaria', models.CharField(default='#2670E8', max_length=7)),
                ('link_diretorio_nextcloud_publico', models.URLField(blank=True)),
                ('link_diretorio_nextcloud_interno', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_configuracao_portal',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('link_url', models.URLField(help_text='Aceita URL externa, incluindo pastas do Nextcloud')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('abrir_em_nova_aba', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='cms.menu')),
            ],
            options={
                'db_table': 'cms_menu',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
