# Generated by Django 5.1.6 on 2026-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icone_classe',
            field=models.CharField(blank=True, help_text='Classe FontAwesome 5 Free, ex: fas fa-folder-open', max_length=80),
        ),
        migrations.AlterField(
            model_name='menu',
            name='abrir_em_nova_aba',
            field=models.BooleanField(default=False, help_text='Marque como True para links externos (ex.: Nextcloud) abrirem fora da SPA.'),
        ),
    ]
