# Generated by Django 5.1.6 on 2026-04-11 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_menu_icone_classe_alter_menu_abrir_em_nova_aba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icone_classe',
            field=models.CharField(blank=True, help_text='Classe FontAwesome 5 Free, ex: fas fa-folder-open', max_length=80, validators=[django.core.validators.RegexValidator(message='Use classes FontAwesome 5 Free no formato: fas fa-folder-open.', regex='^(fas|far|fab)\\s+fa-[a-z0-9-]+$')]),
        ),
    ]
