# Generated by Django 5.1.6 on 2026-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_menu_icone_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem_url', models.CharField(blank=True, max_length=500)),
                ('categoria_texto', models.CharField(max_length=50)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.TextField()),
                ('is_destaque', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_noticia',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
