# Generated by Django 5.1.6 on 2026-04-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinformativo',
            name='icone_url',
            field=models.URLField(blank=True, help_text='URL de icone SVG (ex.: Nextcloud). Prioritario sobre o campo icone.'),
        ),
    ]
