from django.db import migrations

# ---------------------------------------------------------------------------
# SNAPSHOT DETERMINÍSTICO — NÃO importar módulos externos.
# Representa o estado do catálogo na data de criação desta migração (0008).
# Ícones militares adicionados posteriormente estão na migração 0009.
# Ícones da curadoria AMAN estão na migração 0010.
# ---------------------------------------------------------------------------
CATALOG_VERSION = "5.10.2"

_ICONS_SNAPSHOT = [
    # ── Solid (fas) ──────────────────────────────────────────────────────────
    {"style": "fas", "icon_name": "home", "class_name": "fas fa-home", "label": "Home"},
    {"style": "fas", "icon_name": "tachometer-alt", "class_name": "fas fa-tachometer-alt", "label": "Dashboard"},
    {"style": "fas", "icon_name": "user", "class_name": "fas fa-user", "label": "Usuario"},
    {"style": "fas", "icon_name": "users", "class_name": "fas fa-users", "label": "Usuarios"},
    {"style": "fas", "icon_name": "user-shield", "class_name": "fas fa-user-shield", "label": "Usuario seguro"},
    {"style": "fas", "icon_name": "id-card", "class_name": "fas fa-id-card", "label": "Identificacao"},
    {"style": "fas", "icon_name": "id-badge", "class_name": "fas fa-id-badge", "label": "Cracha"},
    {"style": "fas", "icon_name": "address-card", "class_name": "fas fa-address-card", "label": "Cartao contato"},
    {"style": "fas", "icon_name": "cog", "class_name": "fas fa-cog", "label": "Configuracao"},
    {"style": "fas", "icon_name": "cogs", "class_name": "fas fa-cogs", "label": "Configuracoes"},
    {"style": "fas", "icon_name": "tools", "class_name": "fas fa-tools", "label": "Ferramentas"},
    {"style": "fas", "icon_name": "wrench", "class_name": "fas fa-wrench", "label": "Chave"},
    {"style": "fas", "icon_name": "sliders-h", "class_name": "fas fa-sliders-h", "label": "Ajustes"},
    {"style": "fas", "icon_name": "list", "class_name": "fas fa-list", "label": "Lista"},
    {"style": "fas", "icon_name": "list-ul", "class_name": "fas fa-list-ul", "label": "Lista detalhada"},
    {"style": "fas", "icon_name": "th-list", "class_name": "fas fa-th-list", "label": "Lista em blocos"},
    {"style": "fas", "icon_name": "bars", "class_name": "fas fa-bars", "label": "Menu"},
    {"style": "fas", "icon_name": "ellipsis-h", "class_name": "fas fa-ellipsis-h", "label": "Mais opcoes"},
    {"style": "fas", "icon_name": "search", "class_name": "fas fa-search", "label": "Buscar"},
    {"style": "fas", "icon_name": "filter", "class_name": "fas fa-filter", "label": "Filtro"},
    {"style": "fas", "icon_name": "folder", "class_name": "fas fa-folder", "label": "Pasta"},
    {"style": "fas", "icon_name": "folder-open", "class_name": "fas fa-folder-open", "label": "Pasta aberta"},
    {"style": "fas", "icon_name": "folder-plus", "class_name": "fas fa-folder-plus", "label": "Nova pasta"},
    {"style": "fas", "icon_name": "folder-minus", "class_name": "fas fa-folder-minus", "label": "Remover pasta"},
    {"style": "fas", "icon_name": "file", "class_name": "fas fa-file", "label": "Arquivo"},
    {"style": "fas", "icon_name": "file-alt", "class_name": "fas fa-file-alt", "label": "Documento"},
    {"style": "fas", "icon_name": "file-pdf", "class_name": "fas fa-file-pdf", "label": "PDF"},
    {"style": "fas", "icon_name": "file-excel", "class_name": "fas fa-file-excel", "label": "Excel"},
    {"style": "fas", "icon_name": "file-word", "class_name": "fas fa-file-word", "label": "Word"},
    {"style": "fas", "icon_name": "save", "class_name": "fas fa-save", "label": "Salvar"},
    {"style": "fas", "icon_name": "edit", "class_name": "fas fa-edit", "label": "Editar"},
    {"style": "fas", "icon_name": "trash", "class_name": "fas fa-trash", "label": "Excluir"},
    {"style": "fas", "icon_name": "copy", "class_name": "fas fa-copy", "label": "Copiar"},
    {"style": "fas", "icon_name": "cut", "class_name": "fas fa-cut", "label": "Recortar"},
    {"style": "fas", "icon_name": "plus", "class_name": "fas fa-plus", "label": "Adicionar"},
    {"style": "fas", "icon_name": "minus", "class_name": "fas fa-minus", "label": "Remover"},
    {"style": "fas", "icon_name": "check", "class_name": "fas fa-check", "label": "Confirmar"},
    {"style": "fas", "icon_name": "times", "class_name": "fas fa-times", "label": "Fechar"},
    {"style": "fas", "icon_name": "check-circle", "class_name": "fas fa-check-circle", "label": "Sucesso"},
    {"style": "fas", "icon_name": "exclamation-circle", "class_name": "fas fa-exclamation-circle", "label": "Alerta"},
    {"style": "fas", "icon_name": "exclamation-triangle", "class_name": "fas fa-exclamation-triangle", "label": "Atencao"},
    {"style": "fas", "icon_name": "info-circle", "class_name": "fas fa-info-circle", "label": "Informacao"},
    {"style": "fas", "icon_name": "question-circle", "class_name": "fas fa-question-circle", "label": "Ajuda"},
    {"style": "fas", "icon_name": "bell", "class_name": "fas fa-bell", "label": "Notificacao"},
    {"style": "fas", "icon_name": "bell-slash", "class_name": "fas fa-bell-slash", "label": "Sem notificacao"},
    {"style": "fas", "icon_name": "envelope", "class_name": "fas fa-envelope", "label": "Email"},
    {"style": "fas", "icon_name": "envelope-open", "class_name": "fas fa-envelope-open", "label": "Email aberto"},
    {"style": "fas", "icon_name": "phone", "class_name": "fas fa-phone", "label": "Telefone"},
    {"style": "fas", "icon_name": "calendar-alt", "class_name": "fas fa-calendar-alt", "label": "Calendario"},
    {"style": "fas", "icon_name": "calendar-check", "class_name": "fas fa-calendar-check", "label": "Calendario check"},
    {"style": "fas", "icon_name": "calendar-times", "class_name": "fas fa-calendar-times", "label": "Calendario cancelado"},
    {"style": "fas", "icon_name": "clock", "class_name": "fas fa-clock", "label": "Relogio"},
    {"style": "fas", "icon_name": "history", "class_name": "fas fa-history", "label": "Historico"},
    {"style": "fas", "icon_name": "map-marker-alt", "class_name": "fas fa-map-marker-alt", "label": "Localizacao"},
    {"style": "fas", "icon_name": "map", "class_name": "fas fa-map", "label": "Mapa"},
    {"style": "fas", "icon_name": "globe", "class_name": "fas fa-globe", "label": "Mundo"},
    {"style": "fas", "icon_name": "globe-americas", "class_name": "fas fa-globe-americas", "label": "Americas"},
    {"style": "fas", "icon_name": "link", "class_name": "fas fa-link", "label": "Link"},
    {"style": "fas", "icon_name": "external-link-alt", "class_name": "fas fa-external-link-alt", "label": "Link externo"},
    {"style": "fas", "icon_name": "lock", "class_name": "fas fa-lock", "label": "Bloqueado"},
    {"style": "fas", "icon_name": "unlock", "class_name": "fas fa-unlock", "label": "Desbloqueado"},
    {"style": "fas", "icon_name": "shield-alt", "class_name": "fas fa-shield-alt", "label": "Seguranca"},
    {"style": "fas", "icon_name": "key", "class_name": "fas fa-key", "label": "Chave"},
    {"style": "fas", "icon_name": "database", "class_name": "fas fa-database", "label": "Banco de dados"},
    {"style": "fas", "icon_name": "server", "class_name": "fas fa-server", "label": "Servidor"},
    {"style": "fas", "icon_name": "cloud", "class_name": "fas fa-cloud", "label": "Nuvem"},
    {"style": "fas", "icon_name": "cloud-upload-alt", "class_name": "fas fa-cloud-upload-alt", "label": "Nuvem upload"},
    {"style": "fas", "icon_name": "cloud-download-alt", "class_name": "fas fa-cloud-download-alt", "label": "Nuvem download"},
    {"style": "fas", "icon_name": "upload", "class_name": "fas fa-upload", "label": "Upload"},
    {"style": "fas", "icon_name": "download", "class_name": "fas fa-download", "label": "Download"},
    {"style": "fas", "icon_name": "sync", "class_name": "fas fa-sync", "label": "Sincronizar"},
    {"style": "fas", "icon_name": "redo", "class_name": "fas fa-redo", "label": "Refazer"},
    {"style": "fas", "icon_name": "undo", "class_name": "fas fa-undo", "label": "Desfazer"},
    {"style": "fas", "icon_name": "chart-bar", "class_name": "fas fa-chart-bar", "label": "Grafico barras"},
    {"style": "fas", "icon_name": "chart-line", "class_name": "fas fa-chart-line", "label": "Grafico linha"},
    {"style": "fas", "icon_name": "chart-pie", "class_name": "fas fa-chart-pie", "label": "Grafico pizza"},
    {"style": "fas", "icon_name": "chart-area", "class_name": "fas fa-chart-area", "label": "Grafico area"},
    {"style": "fas", "icon_name": "clipboard", "class_name": "fas fa-clipboard", "label": "Area de transferencia"},
    {"style": "fas", "icon_name": "clipboard-check", "class_name": "fas fa-clipboard-check", "label": "Validado"},
    {"style": "fas", "icon_name": "clipboard-list", "class_name": "fas fa-clipboard-list", "label": "Checklist"},
    {"style": "fas", "icon_name": "newspaper", "class_name": "fas fa-newspaper", "label": "Noticias"},
    {"style": "fas", "icon_name": "comment", "class_name": "fas fa-comment", "label": "Comentario"},
    {"style": "fas", "icon_name": "comments", "class_name": "fas fa-comments", "label": "Comentarios"},
    {"style": "fas", "icon_name": "comment-dots", "class_name": "fas fa-comment-dots", "label": "Mensagem"},
    {"style": "fas", "icon_name": "thumbs-up", "class_name": "fas fa-thumbs-up", "label": "Curtir"},
    {"style": "fas", "icon_name": "thumbs-down", "class_name": "fas fa-thumbs-down", "label": "Nao curtir"},
    {"style": "fas", "icon_name": "star", "class_name": "fas fa-star", "label": "Favorito"},
    {"style": "fas", "icon_name": "heart", "class_name": "fas fa-heart", "label": "Destaque"},
    {"style": "fas", "icon_name": "heart-broken", "class_name": "fas fa-heart-broken", "label": "Indisponivel"},
    {"style": "fas", "icon_name": "image", "class_name": "fas fa-image", "label": "Imagem"},
    {"style": "fas", "icon_name": "images", "class_name": "fas fa-images", "label": "Galeria"},
    {"style": "fas", "icon_name": "video", "class_name": "fas fa-video", "label": "Video"},
    {"style": "fas", "icon_name": "camera", "class_name": "fas fa-camera", "label": "Camera"},
    {"style": "fas", "icon_name": "play", "class_name": "fas fa-play", "label": "Play"},
    {"style": "fas", "icon_name": "pause", "class_name": "fas fa-pause", "label": "Pausar"},
    {"style": "fas", "icon_name": "shopping-cart", "class_name": "fas fa-shopping-cart", "label": "Carrinho"},
    {"style": "fas", "icon_name": "cart-plus", "class_name": "fas fa-cart-plus", "label": "Adicionar carrinho"},
    {"style": "fas", "icon_name": "money-bill", "class_name": "fas fa-money-bill", "label": "Financeiro"},
    {"style": "fas", "icon_name": "dollar-sign", "class_name": "fas fa-dollar-sign", "label": "Dinheiro"},
    {"style": "fas", "icon_name": "credit-card", "class_name": "fas fa-credit-card", "label": "Cartao"},
    {"style": "fas", "icon_name": "briefcase", "class_name": "fas fa-briefcase", "label": "Trabalho"},
    {"style": "fas", "icon_name": "briefcase-medical", "class_name": "fas fa-briefcase-medical", "label": "Trabalho medico"},
    {"style": "fas", "icon_name": "book", "class_name": "fas fa-book", "label": "Livro"},
    {"style": "fas", "icon_name": "book-open", "class_name": "fas fa-book-open", "label": "Livro aberto"},
    {"style": "fas", "icon_name": "bookmark", "class_name": "fas fa-bookmark", "label": "Marcador"},
    {"style": "fas", "icon_name": "graduation-cap", "class_name": "fas fa-graduation-cap", "label": "Educacao"},
    {"style": "fas", "icon_name": "hospital", "class_name": "fas fa-hospital", "label": "Hospital"},
    {"style": "fas", "icon_name": "hospital-alt", "class_name": "fas fa-hospital-alt", "label": "Hospital alternativo"},
    {"style": "fas", "icon_name": "stethoscope", "class_name": "fas fa-stethoscope", "label": "Saude"},
    {"style": "fas", "icon_name": "ambulance", "class_name": "fas fa-ambulance", "label": "Ambulancia"},
    {"style": "fas", "icon_name": "medkit", "class_name": "fas fa-medkit", "label": "Kit medico"},
    {"style": "fas", "icon_name": "first-aid", "class_name": "fas fa-first-aid", "label": "Primeiros socorros"},
    {"style": "fas", "icon_name": "heartbeat", "class_name": "fas fa-heartbeat", "label": "Batimento"},
    {"style": "fas", "icon_name": "running", "class_name": "fas fa-running", "label": "Atividade fisica"},
    {"style": "fas", "icon_name": "dumbbell", "class_name": "fas fa-dumbbell", "label": "Treino"},
    {"style": "fas", "icon_name": "bicycle", "class_name": "fas fa-bicycle", "label": "Bicicleta"},
    {"style": "fas", "icon_name": "bus", "class_name": "fas fa-bus", "label": "Onibus"},
    {"style": "fas", "icon_name": "car", "class_name": "fas fa-car", "label": "Carro"},
    {"style": "fas", "icon_name": "plane", "class_name": "fas fa-plane", "label": "Aviao"},
    {"style": "fas", "icon_name": "road", "class_name": "fas fa-road", "label": "Rota"},
    {"style": "fas", "icon_name": "anchor", "class_name": "fas fa-anchor", "label": "Ancora"},
    {"style": "fas", "icon_name": "building", "class_name": "fas fa-building", "label": "Predio"},
    {"style": "fas", "icon_name": "city", "class_name": "fas fa-city", "label": "Cidade"},
    {"style": "fas", "icon_name": "industry", "class_name": "fas fa-industry", "label": "Industria"},
    {"style": "fas", "icon_name": "university", "class_name": "fas fa-university", "label": "Instituicao"},
    {"style": "fas", "icon_name": "leaf", "class_name": "fas fa-leaf", "label": "Sustentabilidade"},
    {"style": "fas", "icon_name": "recycle", "class_name": "fas fa-recycle", "label": "Reciclagem"},
    {"style": "fas", "icon_name": "flag", "class_name": "fas fa-flag", "label": "Bandeira"},
    {"style": "fas", "icon_name": "bullhorn", "class_name": "fas fa-bullhorn", "label": "Comunicado"},
    {"style": "fas", "icon_name": "microphone", "class_name": "fas fa-microphone", "label": "Microfone"},
    {"style": "fas", "icon_name": "podcast", "class_name": "fas fa-podcast", "label": "Podcast"},
    {"style": "fas", "icon_name": "rss", "class_name": "fas fa-rss", "label": "RSS"},
    {"style": "fas", "icon_name": "terminal", "class_name": "fas fa-terminal", "label": "Terminal"},
    {"style": "fas", "icon_name": "code", "class_name": "fas fa-code", "label": "Codigo"},
    {"style": "fas", "icon_name": "code-branch", "class_name": "fas fa-code-branch", "label": "Branch"},
    {"style": "fas", "icon_name": "bug", "class_name": "fas fa-bug", "label": "Bug"},
    {"style": "fas", "icon_name": "tasks", "class_name": "fas fa-tasks", "label": "Tarefas"},
    {"style": "fas", "icon_name": "project-diagram", "class_name": "fas fa-project-diagram", "label": "Fluxo"},
    {"style": "fas", "icon_name": "sitemap", "class_name": "fas fa-sitemap", "label": "Mapa do site"},
    {"style": "fas", "icon_name": "angle-left", "class_name": "fas fa-angle-left", "label": "Seta esquerda"},
    {"style": "fas", "icon_name": "angle-right", "class_name": "fas fa-angle-right", "label": "Seta direita"},
    {"style": "fas", "icon_name": "angle-up", "class_name": "fas fa-angle-up", "label": "Seta cima"},
    {"style": "fas", "icon_name": "angle-down", "class_name": "fas fa-angle-down", "label": "Seta baixo"},
    {"style": "fas", "icon_name": "chevron-left", "class_name": "fas fa-chevron-left", "label": "Voltar"},
    {"style": "fas", "icon_name": "chevron-right", "class_name": "fas fa-chevron-right", "label": "Avancar"},
    {"style": "fas", "icon_name": "chevron-up", "class_name": "fas fa-chevron-up", "label": "Expandir"},
    {"style": "fas", "icon_name": "chevron-down", "class_name": "fas fa-chevron-down", "label": "Recolher"},
    # ── Brands (fab) ─────────────────────────────────────────────────────────
    {"style": "fab", "icon_name": "facebook", "class_name": "fab fa-facebook", "label": "Facebook"},
    {"style": "fab", "icon_name": "facebook-f", "class_name": "fab fa-facebook-f", "label": "Facebook F"},
    {"style": "fab", "icon_name": "instagram", "class_name": "fab fa-instagram", "label": "Instagram"},
    {"style": "fab", "icon_name": "linkedin", "class_name": "fab fa-linkedin", "label": "LinkedIn"},
    {"style": "fab", "icon_name": "linkedin-in", "class_name": "fab fa-linkedin-in", "label": "LinkedIn In"},
    {"style": "fab", "icon_name": "youtube", "class_name": "fab fa-youtube", "label": "YouTube"},
    {"style": "fab", "icon_name": "twitter", "class_name": "fab fa-twitter", "label": "Twitter"},
    {"style": "fab", "icon_name": "whatsapp", "class_name": "fab fa-whatsapp", "label": "WhatsApp"},
    {"style": "fab", "icon_name": "telegram", "class_name": "fab fa-telegram", "label": "Telegram"},
    {"style": "fab", "icon_name": "github", "class_name": "fab fa-github", "label": "GitHub"},
    {"style": "fab", "icon_name": "gitlab", "class_name": "fab fa-gitlab", "label": "GitLab"},
    {"style": "fab", "icon_name": "bitbucket", "class_name": "fab fa-bitbucket", "label": "Bitbucket"},
    {"style": "fab", "icon_name": "docker", "class_name": "fab fa-docker", "label": "Docker"},
    {"style": "fab", "icon_name": "python", "class_name": "fab fa-python", "label": "Python"},
    {"style": "fab", "icon_name": "node-js", "class_name": "fab fa-node-js", "label": "Node.js"},
    {"style": "fab", "icon_name": "react", "class_name": "fab fa-react", "label": "React"},
    {"style": "fab", "icon_name": "angular", "class_name": "fab fa-angular", "label": "Angular"},
    {"style": "fab", "icon_name": "vuejs", "class_name": "fab fa-vuejs", "label": "Vue.js"},
    {"style": "fab", "icon_name": "html5", "class_name": "fab fa-html5", "label": "HTML5"},
    {"style": "fab", "icon_name": "css3", "class_name": "fab fa-css3", "label": "CSS3"},
    {"style": "fab", "icon_name": "js", "class_name": "fab fa-js", "label": "JavaScript"},
    {"style": "fab", "icon_name": "js-square", "class_name": "fab fa-js-square", "label": "JavaScript Square"},
    {"style": "fab", "icon_name": "sass", "class_name": "fab fa-sass", "label": "Sass"},
    {"style": "fab", "icon_name": "bootstrap", "class_name": "fab fa-bootstrap", "label": "Bootstrap"},
    {"style": "fab", "icon_name": "wordpress", "class_name": "fab fa-wordpress", "label": "WordPress"},
    {"style": "fab", "icon_name": "drupal", "class_name": "fab fa-drupal", "label": "Drupal"},
    {"style": "fab", "icon_name": "slack", "class_name": "fab fa-slack", "label": "Slack"},
    {"style": "fab", "icon_name": "discord", "class_name": "fab fa-discord", "label": "Discord"},
    {"style": "fab", "icon_name": "microsoft", "class_name": "fab fa-microsoft", "label": "Microsoft"},
    {"style": "fab", "icon_name": "google", "class_name": "fab fa-google", "label": "Google"},
    {"style": "fab", "icon_name": "google-drive", "class_name": "fab fa-google-drive", "label": "Google Drive"},
    {"style": "fab", "icon_name": "google-play", "class_name": "fab fa-google-play", "label": "Google Play"},
    {"style": "fab", "icon_name": "apple", "class_name": "fab fa-apple", "label": "Apple"},
    {"style": "fab", "icon_name": "android", "class_name": "fab fa-android", "label": "Android"},
    {"style": "fab", "icon_name": "windows", "class_name": "fab fa-windows", "label": "Windows"},
    {"style": "fab", "icon_name": "linux", "class_name": "fab fa-linux", "label": "Linux"},
    {"style": "fab", "icon_name": "aws", "class_name": "fab fa-aws", "label": "AWS"},
    {"style": "fab", "icon_name": "dropbox", "class_name": "fab fa-dropbox", "label": "Dropbox"},
    {"style": "fab", "icon_name": "npm", "class_name": "fab fa-npm", "label": "NPM"},
]


def seed_full_fontawesome_catalog(apps, schema_editor):
    FontAwesomeIcon = apps.get_model("cms", "FontAwesomeIcon")

    FontAwesomeIcon.objects.bulk_create(
        [
            FontAwesomeIcon(
                style=item["style"],
                icon_name=item["icon_name"],
                class_name=item["class_name"],
                label=item["label"],
                version=CATALOG_VERSION,
                ativo=True,
            )
            for item in _ICONS_SNAPSHOT
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_fontawesomeicon"),
    ]

    operations = [
        migrations.RunPython(seed_full_fontawesome_catalog, migrations.RunPython.noop),
    ]
