# Generated by Django 5.1.6 on 2026-04-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_cabecalho_workflow_i18n'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fontawesomeicon',
            new_name='cms_fontawe_style_7f08f0_idx',
            old_name='cms_fontaw_style_a_5c191c_idx',
        ),
        migrations.RenameIndex(
            model_name='fontawesomeicon',
            new_name='cms_fontawe_icon_na_feb9d5_idx',
            old_name='cms_fontaw_icon_na_497f0a_idx',
        ),
    ]
