# Generated by Django 5.1.6 on 2026-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_logsacesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchpadAplicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=255)),
                ('section', models.CharField(choices=[('launchpad', 'Launchpad'), ('legados', 'Legados')], default='launchpad', max_length=20)),
                ('tipo_acesso', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=20)),
                ('rota_interna', models.CharField(blank=True, max_length=255)),
                ('url_externa', models.URLField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('abrir_em_nova_aba', models.BooleanField(default=False)),
                ('grupos_ad_permitidos', models.JSONField(blank=True, default=list, help_text='Lista de grupos AD autorizados (CN ou DN). Vazio libera para todos os autenticados.')),
                ('ordem', models.PositiveIntegerField(default=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aplicativo do Launchpad',
                'verbose_name_plural': 'Aplicativos do Launchpad',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='ldap_grupos_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ldap_ultimo_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
